[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "smelter"
version = "0.0.1"
requires-python = ">=3.11"

[project.scripts]
smelter = "smelter.cli:entrypoint"

[tool.pytest.ini_options]
testpaths = ["tests"]
